---
title: "SPH 215: Geographic Information Systems for Public Health 2026"
---

\

### Professor Peter James
### University of California, Davis
### School of Medicine
### Department of Public Health Sciences

\

Welcome to the SPH 215 website. This website complements the class [Canvas](https://canvas.ucdavis.edu/courses/996070) site.

On this website you will find:

- An abridged syllabus
- Assignment guidelines
- Lab and homework assignment material
- Other useful R related material

On Canvas you will find:

- A detailed syllabus
- Reading material
- Lecture slides
- Project material
- A place to submit your homework
- Grades

\

# About the Class
This 3-unit course introduces the concepts and components of a geographic information system (GIS) for public health. It also teaches the essential skills of operating a functional GIS through the use of R, which is free and open-source software. By completing this course, students will understand the operational processes of spatial data acquisition, editing and QA/QC, spatial data visualization, geocoding, spatial joins and extractions to create exposure metrics, network analysis, spatial clustering analyses, spatial lag analyses, and geographically weighted regression.

\

# Acknowledgements 
The following websites were used in the construction of this course website. My immense thanks go out to the people who invested their time and effort in developing and offering these valuable resources to the public.

- Noli Brazil's [CRD 230: Spatial Methods in Community Research Course](https://crd230.github.io/index.html) (which this website relies **heavily** upon! *Thank you Noli!*)
- Manuel Gimond’s [Intro to GIS and Spatial Analysis](https://mgimond.github.io/Spatial/index.html)
- Claudia Engel’s [Using Spatial Data in R](https://cengel.github.io/R-spatial/)
- Corey Sparks’ [RPubs Labs](https://rpubs.com/corey_sparks)
- Ben Baumer’s [Spatial Data Science Course](https://beanumber.github.io/sds192/)
- Kyle Walker’s [Analyzing US Census Data](https://walker-data.com/census-r/)
