---
title: "Lab 2"
author: "Peter James"
date: "2025-04-10"
output:
  word_document: default
  html_document: default
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(warning=FALSE, message = FALSE)
```

# Lab 2

```{r, eval=FALSE}
install.packages("sf")
```

```{r}
library(sf)
library(MapGAM)
library(tidyverse)
library(tidycensus)
library(tidygeocoder)
library(flextable)
library(tmap)
```

## Geocoding

Download file
```{r}
download.file("https://raw.githubusercontent.com/pjames-ucdavis/SPH215/refs/heads/main/san_francisco_active_marijuana_retailers.csv", "san_francisco_active_marijuana_retailers.csv", mode = "wb")

sf_mj <- read_csv("san_francisco_active_marijuana_retailers.csv")
```

Look at data
```{r}
head(sf_mj)
```

Premise address
```{r}
head(sf_mj$`Premise Address`)
```
Drop County: SAN FRANCISCO
```{r}
sf_mj$`Premise Address` <- gsub(" County: SAN FRANCISCO","", sf_mj$`Premise Address`)
head(sf_mj$`Premise Address`)
```
Let's geocode
```{r}
sf_mj_geo      <- geocode(sf_mj, "Premise Address",
                          method = "osm")
```

Check data
```{r}
summary(sf_mj_geo$long)
```
Geocode with ArcGIS geocoder
```{r}
sf_mj_geo_arc      <- geocode(sf_mj, "Premise Address",
                          method = "arcgis")
```

Look at data
```{r}
head(sf_mj_geo_arc)
summary(sf_mj_geo_arc$lat)
```

Plot geocodes
```{r}
plot(sf_mj_geo_arc$long, sf_mj_geo_arc$lat)

```

## MapGAM

### Bring in CAdata
```{r}
data(CAdata)
ca_pts <- CAdata
summary(ca_pts)
```

Make CAData spatial
```{r}
ca_pts <- st_as_sf(CAdata, coords=c("X","Y"))
st_crs(ca_pts)
```

Add CRS
```{r}
lcc_proj <- "+proj=lcc +lat_1=40 +lat_2=41.66666666666666 
             +lat_0=39.33333333333334 +lon_0=-122 +x_0=2000000 
             +y_0=500000.0000000002 +ellps=GRS80 
             +datum=NAD83 +units=m +no_defs"

ca_pts_crs <- st_set_crs(ca_pts, lcc_proj)
summary(ca_pts_crs) 
```
Check CRS
```{r}
st_crs(ca_pts_crs)
```

Let's map this

```{r}
tmap_mode("view")
cancer_map = tm_shape(ca_pts_crs) + tm_dots(size=0.5)
cancer_map
```

Change our map
```{r}
cancer_map_small = tm_shape(ca_pts_crs) + tm_dots(col = "purple", size = 0.3, alpha = 0.5)
cancer_map_small
```

Plot by attribute
```{r}
cancer_map_events = tm_shape(ca_pts_crs) + tm_dots(size=0.3, col="event", style="cat")
cancer_map_events
```

Plot with our colors
```{r}
cancer_map_events_rg = tm_shape(ca_pts_crs) + tm_dots(col = "event", palette = c("0" = "gray", "1" = "red"), style="cat")
cancer_map_events_rg
```

